root://cmseos.fnal.gov//store/user/lpcsusyhad/Stop_production/Spring16_80X_Nov_2016_Ntp_v11X_new_IDs/MET/Spring16_80X_Nov_2016_Ntp_v11p0_new_IDs_MET-Run2016G-PromptReco-v1/161128_201434/0004/stopFlatNtuples_4165.root
root://cmseos.fnal.gov//store/user/lpcsusyhad/Stop_production/Spring16_80X_Nov_2016_Ntp_v11X_new_IDs/MET/Spring16_80X_Nov_2016_Ntp_v11p0_new_IDs_MET-Run2016G-PromptReco-v1/161128_201434/0004/stopFlatNtuples_4166.root
root://cmseos.fnal.gov//store/user/lpcsusyhad/Stop_production/Spring16_80X_Nov_2016_Ntp_v11X_new_IDs/MET/Spring16_80X_Nov_2016_Ntp_v11p0_new_IDs_MET-Run2016G-PromptReco-v1/161128_201434/0004/stopFlatNtuples_4167.root
root://cmseos.fnal.gov//store/user/lpcsusyhad/Stop_production/Spring16_80X_Nov_2016_Ntp_v11X_new_IDs/MET/Spring16_80X_Nov_2016_Ntp_v11p0_new_IDs_MET-Run2016G-PromptReco-v1/161128_201434/0004/stopFlatNtuples_4168.root
root://cmseos.fnal.gov//store/user/lpcsusyhad/Stop_production/Spring16_80X_Nov_2016_Ntp_v11X_new_IDs/MET/Spring16_80X_Nov_2016_Ntp_v11p0_new_IDs_MET-Run2016G-PromptReco-v1/161128_201434/0004/stopFlatNtuples_4169.root
root://cmseos.fnal.gov//store/user/lpcsusyhad/Stop_production/Spring16_80X_Nov_2016_Ntp_v11X_new_IDs/MET/Spring16_80X_Nov_2016_Ntp_v11p0_new_IDs_MET-Run2016G-PromptReco-v1/161128_201434/0004/stopFlatNtuples_4170.root
root://cmseos.fnal.gov//store/user/lpcsusyhad/Stop_production/Spring16_80X_Nov_2016_Ntp_v11X_new_IDs/MET/Spring16_80X_Nov_2016_Ntp_v11p0_new_IDs_MET-Run2016G-PromptReco-v1/161128_201434/0004/stopFlatNtuples_4171.root
root://cmseos.fnal.gov//store/user/lpcsusyhad/Stop_production/Spring16_80X_Nov_2016_Ntp_v11X_new_IDs/MET/Spring16_80X_Nov_2016_Ntp_v11p0_new_IDs_MET-Run2016G-PromptReco-v1/161128_201434/0004/stopFlatNtuples_4172.root
root://cmseos.fnal.gov//store/user/lpcsusyhad/Stop_production/Spring16_80X_Nov_2016_Ntp_v11X_new_IDs/MET/Spring16_80X_Nov_2016_Ntp_v11p0_new_IDs_MET-Run2016G-PromptReco-v1/161128_201434/0004/stopFlatNtuples_4173.root
root://cmseos.fnal.gov//store/user/lpcsusyhad/Stop_production/Spring16_80X_Nov_2016_Ntp_v11X_new_IDs/MET/Spring16_80X_Nov_2016_Ntp_v11p0_new_IDs_MET-Run2016G-PromptReco-v1/161128_201434/0004/stopFlatNtuples_4174.root
root://cmseos.fnal.gov//store/user/lpcsusyhad/Stop_production/Spring16_80X_Nov_2016_Ntp_v11X_new_IDs/MET/Spring16_80X_Nov_2016_Ntp_v11p0_new_IDs_MET-Run2016G-PromptReco-v1/161128_201434/0004/stopFlatNtuples_4175.root
root://cmseos.fnal.gov//store/user/lpcsusyhad/Stop_production/Spring16_80X_Nov_2016_Ntp_v11X_new_IDs/MET/Spring16_80X_Nov_2016_Ntp_v11p0_new_IDs_MET-Run2016G-PromptReco-v1/161128_201434/0004/stopFlatNtuples_4176.root
root://cmseos.fnal.gov//store/user/lpcsusyhad/Stop_production/Spring16_80X_Nov_2016_Ntp_v11X_new_IDs/MET/Spring16_80X_Nov_2016_Ntp_v11p0_new_IDs_MET-Run2016G-PromptReco-v1/161128_201434/0004/stopFlatNtuples_4177.root
root://cmseos.fnal.gov//store/user/lpcsusyhad/Stop_production/Spring16_80X_Nov_2016_Ntp_v11X_new_IDs/MET/Spring16_80X_Nov_2016_Ntp_v11p0_new_IDs_MET-Run2016G-PromptReco-v1/161128_201434/0004/stopFlatNtuples_4178.root
root://cmseos.fnal.gov//store/user/lpcsusyhad/Stop_production/Spring16_80X_Nov_2016_Ntp_v11X_new_IDs/MET/Spring16_80X_Nov_2016_Ntp_v11p0_new_IDs_MET-Run2016G-PromptReco-v1/161128_201434/0004/stopFlatNtuples_4179.root
root://cmseos.fnal.gov//store/user/lpcsusyhad/Stop_production/Spring16_80X_Nov_2016_Ntp_v11X_new_IDs/MET/Spring16_80X_Nov_2016_Ntp_v11p0_new_IDs_MET-Run2016G-PromptReco-v1/161128_201434/0004/stopFlatNtuples_4180.root
root://cmseos.fnal.gov//store/user/lpcsusyhad/Stop_production/Spring16_80X_Nov_2016_Ntp_v11X_new_IDs/MET/Spring16_80X_Nov_2016_Ntp_v11p0_new_IDs_MET-Run2016G-PromptReco-v1/161128_201434/0004/stopFlatNtuples_4181.root
root://cmseos.fnal.gov//store/user/lpcsusyhad/Stop_production/Spring16_80X_Nov_2016_Ntp_v11X_new_IDs/MET/Spring16_80X_Nov_2016_Ntp_v11p0_new_IDs_MET-Run2016G-PromptReco-v1/161128_201434/0004/stopFlatNtuples_4182.root
root://cmseos.fnal.gov//store/user/lpcsusyhad/Stop_production/Spring16_80X_Nov_2016_Ntp_v11X_new_IDs/MET/Spring16_80X_Nov_2016_Ntp_v11p0_new_IDs_MET-Run2016G-PromptReco-v1/161128_201434/0004/stopFlatNtuples_4183.root
root://cmseos.fnal.gov//store/user/lpcsusyhad/Stop_production/Spring16_80X_Nov_2016_Ntp_v11X_new_IDs/MET/Spring16_80X_Nov_2016_Ntp_v11p0_new_IDs_MET-Run2016G-PromptReco-v1/161128_201434/0004/stopFlatNtuples_4184.root
root://cmseos.fnal.gov//store/user/lpcsusyhad/Stop_production/Spring16_80X_Nov_2016_Ntp_v11X_new_IDs/MET/Spring16_80X_Nov_2016_Ntp_v11p0_new_IDs_MET-Run2016G-PromptReco-v1/161128_201434/0004/stopFlatNtuples_4185.root
root://cmseos.fnal.gov//store/user/lpcsusyhad/Stop_production/Spring16_80X_Nov_2016_Ntp_v11X_new_IDs/MET/Spring16_80X_Nov_2016_Ntp_v11p0_new_IDs_MET-Run2016G-PromptReco-v1/161128_201434/0004/stopFlatNtuples_4186.root
root://cmseos.fnal.gov//store/user/lpcsusyhad/Stop_production/Spring16_80X_Nov_2016_Ntp_v11X_new_IDs/MET/Spring16_80X_Nov_2016_Ntp_v11p0_new_IDs_MET-Run2016G-PromptReco-v1/161128_201434/0004/stopFlatNtuples_4187.root
root://cmseos.fnal.gov//store/user/lpcsusyhad/Stop_production/Spring16_80X_Nov_2016_Ntp_v11X_new_IDs/MET/Spring16_80X_Nov_2016_Ntp_v11p0_new_IDs_MET-Run2016G-PromptReco-v1/161128_201434/0004/stopFlatNtuples_4188.root
root://cmseos.fnal.gov//store/user/lpcsusyhad/Stop_production/Spring16_80X_Nov_2016_Ntp_v11X_new_IDs/MET/Spring16_80X_Nov_2016_Ntp_v11p0_new_IDs_MET-Run2016G-PromptReco-v1/161128_201434/0004/stopFlatNtuples_4189.root
root://cmseos.fnal.gov//store/user/lpcsusyhad/Stop_production/Spring16_80X_Nov_2016_Ntp_v11X_new_IDs/MET/Spring16_80X_Nov_2016_Ntp_v11p0_new_IDs_MET-Run2016G-PromptReco-v1/161128_201434/0004/stopFlatNtuples_4190.root
root://cmseos.fnal.gov//store/user/lpcsusyhad/Stop_production/Spring16_80X_Nov_2016_Ntp_v11X_new_IDs/MET/Spring16_80X_Nov_2016_Ntp_v11p0_new_IDs_MET-Run2016G-PromptReco-v1/161128_201434/0004/stopFlatNtuples_4191.root
root://cmseos.fnal.gov//store/user/lpcsusyhad/Stop_production/Spring16_80X_Nov_2016_Ntp_v11X_new_IDs/MET/Spring16_80X_Nov_2016_Ntp_v11p0_new_IDs_MET-Run2016G-PromptReco-v1/161128_201434/0004/stopFlatNtuples_4192.root
root://cmseos.fnal.gov//store/user/lpcsusyhad/Stop_production/Spring16_80X_Nov_2016_Ntp_v11X_new_IDs/MET/Spring16_80X_Nov_2016_Ntp_v11p0_new_IDs_MET-Run2016G-PromptReco-v1/161128_201434/0004/stopFlatNtuples_4193.root
root://cmseos.fnal.gov//store/user/lpcsusyhad/Stop_production/Spring16_80X_Nov_2016_Ntp_v11X_new_IDs/MET/Spring16_80X_Nov_2016_Ntp_v11p0_new_IDs_MET-Run2016G-PromptReco-v1/161128_201434/0004/stopFlatNtuples_4194.root
root://cmseos.fnal.gov//store/user/lpcsusyhad/Stop_production/Spring16_80X_Nov_2016_Ntp_v11X_new_IDs/MET/Spring16_80X_Nov_2016_Ntp_v11p0_new_IDs_MET-Run2016G-PromptReco-v1/161128_201434/0004/stopFlatNtuples_4195.root
root://cmseos.fnal.gov//store/user/lpcsusyhad/Stop_production/Spring16_80X_Nov_2016_Ntp_v11X_new_IDs/MET/Spring16_80X_Nov_2016_Ntp_v11p0_new_IDs_MET-Run2016G-PromptReco-v1/161128_201434/0004/stopFlatNtuples_4196.root
root://cmseos.fnal.gov//store/user/lpcsusyhad/Stop_production/Spring16_80X_Nov_2016_Ntp_v11X_new_IDs/MET/Spring16_80X_Nov_2016_Ntp_v11p0_new_IDs_MET-Run2016G-PromptReco-v1/161128_201434/0004/stopFlatNtuples_4197.root
root://cmseos.fnal.gov//store/user/lpcsusyhad/Stop_production/Spring16_80X_Nov_2016_Ntp_v11X_new_IDs/MET/Spring16_80X_Nov_2016_Ntp_v11p0_new_IDs_MET-Run2016G-PromptReco-v1/161128_201434/0004/stopFlatNtuples_4198.root
root://cmseos.fnal.gov//store/user/lpcsusyhad/Stop_production/Spring16_80X_Nov_2016_Ntp_v11X_new_IDs/MET/Spring16_80X_Nov_2016_Ntp_v11p0_new_IDs_MET-Run2016G-PromptReco-v1/161128_201434/0004/stopFlatNtuples_4199.root
root://cmseos.fnal.gov//store/user/lpcsusyhad/Stop_production/Spring16_80X_Nov_2016_Ntp_v11X_new_IDs/MET/Spring16_80X_Nov_2016_Ntp_v11p0_new_IDs_MET-Run2016G-PromptReco-v1/161128_201434/0004/stopFlatNtuples_4200.root
root://cmseos.fnal.gov//store/user/lpcsusyhad/Stop_production/Spring16_80X_Nov_2016_Ntp_v11X_new_IDs/MET/Spring16_80X_Nov_2016_Ntp_v11p0_new_IDs_MET-Run2016G-PromptReco-v1/161128_201434/0004/stopFlatNtuples_4201.root
root://cmseos.fnal.gov//store/user/lpcsusyhad/Stop_production/Spring16_80X_Nov_2016_Ntp_v11X_new_IDs/MET/Spring16_80X_Nov_2016_Ntp_v11p0_new_IDs_MET-Run2016G-PromptReco-v1/161128_201434/0004/stopFlatNtuples_4202.root
root://cmseos.fnal.gov//store/user/lpcsusyhad/Stop_production/Spring16_80X_Nov_2016_Ntp_v11X_new_IDs/MET/Spring16_80X_Nov_2016_Ntp_v11p0_new_IDs_MET-Run2016G-PromptReco-v1/161128_201434/0004/stopFlatNtuples_4203.root
root://cmseos.fnal.gov//store/user/lpcsusyhad/Stop_production/Spring16_80X_Nov_2016_Ntp_v11X_new_IDs/MET/Spring16_80X_Nov_2016_Ntp_v11p0_new_IDs_MET-Run2016G-PromptReco-v1/161128_201434/0004/stopFlatNtuples_4204.root
