void _ntopjets_BasicCheck()
{
//=========Macro generated from canvas: c/A Simple Graph Example
//=========  (Mon Feb 13 05:57:39 2017) by ROOT version6.06/01
   TCanvas *c = new TCanvas("c", "A Simple Graph Example",0,0,700,500);
   gStyle->SetOptStat(0);
   c->SetHighLightColor(2);
   c->Range(0,0,1,1);
   c->SetFillColor(0);
   c->SetBorderMode(0);
   c->SetBorderSize(2);
   c->SetFrameBorderMode(0);
  
// ------------>Primitives in pad: 
   TPad *pad = new TPad("", "",0,0.2,1,1);
   pad->Draw();
   pad->cd();
   pad->Range(0.375,-46.13171,6.625,9178.714);
   pad->SetFillColor(0);
   pad->SetBorderMode(0);
   pad->SetBorderSize(5);
   pad->SetBottomMargin(0.005);
   pad->SetFrameBorderMode(0);
   pad->SetFrameBorderMode(0);
   
   THStack *hs_MC = new THStack();
   hs_MC->SetName("hs_MC");
   hs_MC->SetTitle("");
   
   TH1F *hs_MC_stack_6 = new TH1F("hs_MC_stack_6","",5,1,6);
   hs_MC_stack_6->SetMinimum(-0.007478935);
   hs_MC_stack_6->SetMaximum(8256.229);
   hs_MC_stack_6->SetDirectory(0);
   hs_MC_stack_6->SetStats(0);

   Int_t ci;      // for color index setting
   TColor *color; // for color definition with alpha
   ci = TColor::GetColor("#000099");
   hs_MC_stack_6->SetLineColor(ci);
   hs_MC_stack_6->GetXaxis()->SetLabelFont(42);
   hs_MC_stack_6->GetXaxis()->SetLabelSize(0.035);
   hs_MC_stack_6->GetXaxis()->SetTitleSize(0.035);
   hs_MC_stack_6->GetXaxis()->SetTitleFont(42);
   hs_MC_stack_6->GetYaxis()->SetLabelFont(42);
   hs_MC_stack_6->GetYaxis()->SetLabelSize(0.035);
   hs_MC_stack_6->GetYaxis()->SetTitleSize(0.035);
   hs_MC_stack_6->GetYaxis()->SetTitleFont(42);
   hs_MC_stack_6->GetZaxis()->SetLabelFont(42);
   hs_MC_stack_6->GetZaxis()->SetLabelSize(0.035);
   hs_MC_stack_6->GetZaxis()->SetTitleSize(0.035);
   hs_MC_stack_6->GetZaxis()->SetTitleFont(42);
   hs_MC->SetHistogram(hs_MC_stack_6);
   
   
   TH1D *h_b_ntopjets_MC_LL__41 = new TH1D("h_b_ntopjets_MC_LL__41","",5,1,6);
   h_b_ntopjets_MC_LL__41->SetBinContent(1,1132.654);
   h_b_ntopjets_MC_LL__41->SetBinContent(2,155.0633);
   h_b_ntopjets_MC_LL__41->SetBinContent(3,3.734766);
   h_b_ntopjets_MC_LL__41->SetBinError(1,11.2594);
   h_b_ntopjets_MC_LL__41->SetBinError(2,4.109235);
   h_b_ntopjets_MC_LL__41->SetBinError(3,0.64355);
   h_b_ntopjets_MC_LL__41->SetEntries(17182);
   h_b_ntopjets_MC_LL__41->SetFillColor(2);
   h_b_ntopjets_MC_LL__41->SetLineColor(2);
   h_b_ntopjets_MC_LL__41->GetXaxis()->SetLabelFont(42);
   h_b_ntopjets_MC_LL__41->GetXaxis()->SetLabelSize(0.035);
   h_b_ntopjets_MC_LL__41->GetXaxis()->SetTitleSize(0.035);
   h_b_ntopjets_MC_LL__41->GetXaxis()->SetTitleFont(42);
   h_b_ntopjets_MC_LL__41->GetYaxis()->SetLabelFont(42);
   h_b_ntopjets_MC_LL__41->GetYaxis()->SetLabelSize(0.035);
   h_b_ntopjets_MC_LL__41->GetYaxis()->SetTitleSize(0.035);
   h_b_ntopjets_MC_LL__41->GetYaxis()->SetTitleFont(42);
   h_b_ntopjets_MC_LL__41->GetZaxis()->SetLabelFont(42);
   h_b_ntopjets_MC_LL__41->GetZaxis()->SetLabelSize(0.035);
   h_b_ntopjets_MC_LL__41->GetZaxis()->SetTitleSize(0.035);
   h_b_ntopjets_MC_LL__41->GetZaxis()->SetTitleFont(42);
   hs_MC->Add(h_b_ntopjets_MC_LL,"");
   
   TH1D *h_b_ntopjets_MC_HadTau__42 = new TH1D("h_b_ntopjets_MC_HadTau__42","",5,1,6);
   h_b_ntopjets_MC_HadTau__42->SetBinContent(1,1673.677);
   h_b_ntopjets_MC_HadTau__42->SetBinContent(2,312.8006);
   h_b_ntopjets_MC_HadTau__42->SetBinContent(3,5.470424);
   h_b_ntopjets_MC_HadTau__42->SetBinError(1,14.00827);
   h_b_ntopjets_MC_HadTau__42->SetBinError(2,5.944312);
   h_b_ntopjets_MC_HadTau__42->SetBinError(3,0.7879584);
   h_b_ntopjets_MC_HadTau__42->SetEntries(25068);
   h_b_ntopjets_MC_HadTau__42->SetFillColor(3);
   h_b_ntopjets_MC_HadTau__42->SetLineColor(3);
   h_b_ntopjets_MC_HadTau__42->GetXaxis()->SetLabelFont(42);
   h_b_ntopjets_MC_HadTau__42->GetXaxis()->SetLabelSize(0.035);
   h_b_ntopjets_MC_HadTau__42->GetXaxis()->SetTitleSize(0.035);
   h_b_ntopjets_MC_HadTau__42->GetXaxis()->SetTitleFont(42);
   h_b_ntopjets_MC_HadTau__42->GetYaxis()->SetLabelFont(42);
   h_b_ntopjets_MC_HadTau__42->GetYaxis()->SetLabelSize(0.035);
   h_b_ntopjets_MC_HadTau__42->GetYaxis()->SetTitleSize(0.035);
   h_b_ntopjets_MC_HadTau__42->GetYaxis()->SetTitleFont(42);
   h_b_ntopjets_MC_HadTau__42->GetZaxis()->SetLabelFont(42);
   h_b_ntopjets_MC_HadTau__42->GetZaxis()->SetLabelSize(0.035);
   h_b_ntopjets_MC_HadTau__42->GetZaxis()->SetTitleSize(0.035);
   h_b_ntopjets_MC_HadTau__42->GetZaxis()->SetTitleFont(42);
   hs_MC->Add(h_b_ntopjets_MC_HadTau,"");
   
   TH1D *h_b_ntopjets_MC_Zinv__43 = new TH1D("h_b_ntopjets_MC_Zinv__43","",5,1,6);
   h_b_ntopjets_MC_Zinv__43->SetBinContent(1,208.424);
   h_b_ntopjets_MC_Zinv__43->SetBinContent(2,8.396364);
   h_b_ntopjets_MC_Zinv__43->SetBinContent(3,0.07328388);
   h_b_ntopjets_MC_Zinv__43->SetBinError(1,2.698772);
   h_b_ntopjets_MC_Zinv__43->SetBinError(2,0.4892791);
   h_b_ntopjets_MC_Zinv__43->SetBinError(3,0.04120869);
   h_b_ntopjets_MC_Zinv__43->SetEntries(10169);
   h_b_ntopjets_MC_Zinv__43->SetFillColor(4);
   h_b_ntopjets_MC_Zinv__43->SetLineColor(4);
   h_b_ntopjets_MC_Zinv__43->GetXaxis()->SetLabelFont(42);
   h_b_ntopjets_MC_Zinv__43->GetXaxis()->SetLabelSize(0.035);
   h_b_ntopjets_MC_Zinv__43->GetXaxis()->SetTitleSize(0.035);
   h_b_ntopjets_MC_Zinv__43->GetXaxis()->SetTitleFont(42);
   h_b_ntopjets_MC_Zinv__43->GetYaxis()->SetLabelFont(42);
   h_b_ntopjets_MC_Zinv__43->GetYaxis()->SetLabelSize(0.035);
   h_b_ntopjets_MC_Zinv__43->GetYaxis()->SetTitleSize(0.035);
   h_b_ntopjets_MC_Zinv__43->GetYaxis()->SetTitleFont(42);
   h_b_ntopjets_MC_Zinv__43->GetZaxis()->SetLabelFont(42);
   h_b_ntopjets_MC_Zinv__43->GetZaxis()->SetLabelSize(0.035);
   h_b_ntopjets_MC_Zinv__43->GetZaxis()->SetTitleSize(0.035);
   h_b_ntopjets_MC_Zinv__43->GetZaxis()->SetTitleFont(42);
   hs_MC->Add(h_b_ntopjets_MC_Zinv,"");
   
   TH1D *h_b_ntopjets_MC_QCD__44 = new TH1D("h_b_ntopjets_MC_QCD__44","",5,1,6);
   h_b_ntopjets_MC_QCD__44->SetBinContent(1,4843.705);
   h_b_ntopjets_MC_QCD__44->SetBinContent(2,276.8889);
   h_b_ntopjets_MC_QCD__44->SetBinContent(3,1.444612);
   h_b_ntopjets_MC_QCD__44->SetBinError(1,122.913);
   h_b_ntopjets_MC_QCD__44->SetBinError(2,24.99875);
   h_b_ntopjets_MC_QCD__44->SetBinError(3,0.550804);
   h_b_ntopjets_MC_QCD__44->SetEntries(8073);
   h_b_ntopjets_MC_QCD__44->SetFillColor(5);
   h_b_ntopjets_MC_QCD__44->SetLineColor(5);
   h_b_ntopjets_MC_QCD__44->GetXaxis()->SetLabelFont(42);
   h_b_ntopjets_MC_QCD__44->GetXaxis()->SetLabelSize(0.035);
   h_b_ntopjets_MC_QCD__44->GetXaxis()->SetTitleSize(0.035);
   h_b_ntopjets_MC_QCD__44->GetXaxis()->SetTitleFont(42);
   h_b_ntopjets_MC_QCD__44->GetYaxis()->SetLabelFont(42);
   h_b_ntopjets_MC_QCD__44->GetYaxis()->SetLabelSize(0.035);
   h_b_ntopjets_MC_QCD__44->GetYaxis()->SetTitleSize(0.035);
   h_b_ntopjets_MC_QCD__44->GetYaxis()->SetTitleFont(42);
   h_b_ntopjets_MC_QCD__44->GetZaxis()->SetLabelFont(42);
   h_b_ntopjets_MC_QCD__44->GetZaxis()->SetLabelSize(0.035);
   h_b_ntopjets_MC_QCD__44->GetZaxis()->SetTitleSize(0.035);
   h_b_ntopjets_MC_QCD__44->GetZaxis()->SetTitleFont(42);
   hs_MC->Add(h_b_ntopjets_MC_QCD,"");
   
   TH1D *h_b_ntopjets_MC_TTZ__45 = new TH1D("h_b_ntopjets_MC_TTZ__45","",5,1,6);
   h_b_ntopjets_MC_TTZ__45->SetBinContent(1,4.614965);
   h_b_ntopjets_MC_TTZ__45->SetBinContent(2,-0.949659);
   h_b_ntopjets_MC_TTZ__45->SetBinContent(3,-0.2932924);
   h_b_ntopjets_MC_TTZ__45->SetBinContent(4,-0.007478935);
   h_b_ntopjets_MC_TTZ__45->SetBinError(1,2.457361);
   h_b_ntopjets_MC_TTZ__45->SetBinError(2,0.9863462);
   h_b_ntopjets_MC_TTZ__45->SetBinError(3,0.1902046);
   h_b_ntopjets_MC_TTZ__45->SetBinError(4,0.01057286);
   h_b_ntopjets_MC_TTZ__45->SetEntries(12951);
   h_b_ntopjets_MC_TTZ__45->SetFillColor(6);
   h_b_ntopjets_MC_TTZ__45->SetLineColor(6);
   h_b_ntopjets_MC_TTZ__45->GetXaxis()->SetLabelFont(42);
   h_b_ntopjets_MC_TTZ__45->GetXaxis()->SetLabelSize(0.035);
   h_b_ntopjets_MC_TTZ__45->GetXaxis()->SetTitleSize(0.035);
   h_b_ntopjets_MC_TTZ__45->GetXaxis()->SetTitleFont(42);
   h_b_ntopjets_MC_TTZ__45->GetYaxis()->SetLabelFont(42);
   h_b_ntopjets_MC_TTZ__45->GetYaxis()->SetLabelSize(0.035);
   h_b_ntopjets_MC_TTZ__45->GetYaxis()->SetTitleSize(0.035);
   h_b_ntopjets_MC_TTZ__45->GetYaxis()->SetTitleFont(42);
   h_b_ntopjets_MC_TTZ__45->GetZaxis()->SetLabelFont(42);
   h_b_ntopjets_MC_TTZ__45->GetZaxis()->SetLabelSize(0.035);
   h_b_ntopjets_MC_TTZ__45->GetZaxis()->SetTitleSize(0.035);
   h_b_ntopjets_MC_TTZ__45->GetZaxis()->SetTitleFont(42);
   hs_MC->Add(h_b_ntopjets_MC_TTZ,"");
   hs_MC->Draw("hist");
   
   TH1D *h_b_ntopjets_Data__46 = new TH1D("h_b_ntopjets_Data__46","",5,1,6);
   h_b_ntopjets_Data__46->SetBinContent(1,7097);
   h_b_ntopjets_Data__46->SetBinContent(2,659);
   h_b_ntopjets_Data__46->SetBinContent(3,13);
   h_b_ntopjets_Data__46->SetBinError(1,84.24369);
   h_b_ntopjets_Data__46->SetBinError(2,25.671);
   h_b_ntopjets_Data__46->SetBinError(3,3.605551);
   h_b_ntopjets_Data__46->SetEntries(7769);
   h_b_ntopjets_Data__46->SetLineWidth(3);
   h_b_ntopjets_Data__46->GetXaxis()->SetTitle("Number of Top jets");
   h_b_ntopjets_Data__46->GetXaxis()->SetRange(1,5);
   h_b_ntopjets_Data__46->GetXaxis()->SetLabelFont(42);
   h_b_ntopjets_Data__46->GetXaxis()->SetLabelSize(0.035);
   h_b_ntopjets_Data__46->GetXaxis()->SetTitleSize(0.035);
   h_b_ntopjets_Data__46->GetXaxis()->SetTitleFont(42);
   h_b_ntopjets_Data__46->GetYaxis()->SetLabelFont(42);
   h_b_ntopjets_Data__46->GetYaxis()->SetLabelSize(0.035);
   h_b_ntopjets_Data__46->GetYaxis()->SetTitleSize(0.035);
   h_b_ntopjets_Data__46->GetYaxis()->SetTitleFont(42);
   h_b_ntopjets_Data__46->GetZaxis()->SetLabelFont(42);
   h_b_ntopjets_Data__46->GetZaxis()->SetLabelSize(0.035);
   h_b_ntopjets_Data__46->GetZaxis()->SetTitleSize(0.035);
   h_b_ntopjets_Data__46->GetZaxis()->SetTitleFont(42);
   h_b_ntopjets_Data__46->Draw("same e0");
   pad->Modified();
   c->cd();
  
// ------------>Primitives in pad: ratio
   TPad *ratio = new TPad("ratio", "",0,0,1,0.2);
   ratio->Draw();
   ratio->cd();
   ratio->Range(0.375,-1.857143,6.625,1);
   ratio->SetFillColor(0);
   ratio->SetBorderMode(0);
   ratio->SetBorderSize(5);
   ratio->SetTopMargin(0);
   ratio->SetBottomMargin(0.3);
   ratio->SetFrameBorderMode(0);
   ratio->SetFrameBorderMode(0);
   
   TH1D *h_b_ntopjets_Data_copy__47 = new TH1D("h_b_ntopjets_Data_copy__47","",5,1,6);
   h_b_ntopjets_Data_copy__47->SetBinContent(1,-0.09742695);
   h_b_ntopjets_Data_copy__47->SetBinContent(2,-0.1239026);
   h_b_ntopjets_Data_copy__47->SetBinContent(3,0.2464293);
   h_b_ntopjets_Data_copy__47->SetBinContent(4,-1);
   h_b_ntopjets_Data_copy__47->SetBinError(1,0.01915583);
   h_b_ntopjets_Data_copy__47->SetBinError(2,0.04880645);
   h_b_ntopjets_Data_copy__47->SetBinError(3,0.3645915);
   h_b_ntopjets_Data_copy__47->SetBinError(4,1.999253);
   h_b_ntopjets_Data_copy__47->SetMinimum(-1);
   h_b_ntopjets_Data_copy__47->SetMaximum(1);
   h_b_ntopjets_Data_copy__47->SetEntries(0.9749002);
   h_b_ntopjets_Data_copy__47->SetDirectory(0);
   h_b_ntopjets_Data_copy__47->SetStats(0);
   h_b_ntopjets_Data_copy__47->SetLineWidth(3);
   h_b_ntopjets_Data_copy__47->SetMarkerStyle(7);
   h_b_ntopjets_Data_copy__47->GetXaxis()->SetTitle("Number of Top jets");
   h_b_ntopjets_Data_copy__47->GetXaxis()->SetRange(1,5);
   h_b_ntopjets_Data_copy__47->GetXaxis()->SetLabelFont(42);
   h_b_ntopjets_Data_copy__47->GetXaxis()->SetLabelOffset(0.02);
   h_b_ntopjets_Data_copy__47->GetXaxis()->SetLabelSize(0.14);
   h_b_ntopjets_Data_copy__47->GetXaxis()->SetTitleSize(0.15);
   h_b_ntopjets_Data_copy__47->GetXaxis()->SetTickLength(0.12);
   h_b_ntopjets_Data_copy__47->GetXaxis()->SetTitleFont(42);
   h_b_ntopjets_Data_copy__47->GetYaxis()->SetTitle("(Data-MC)/MC");
   h_b_ntopjets_Data_copy__47->GetYaxis()->SetNdivisions(8);
   h_b_ntopjets_Data_copy__47->GetYaxis()->SetLabelFont(42);
   h_b_ntopjets_Data_copy__47->GetYaxis()->SetLabelSize(0.07);
   h_b_ntopjets_Data_copy__47->GetYaxis()->SetTitleSize(0.08);
   h_b_ntopjets_Data_copy__47->GetYaxis()->SetTitleOffset(0.3);
   h_b_ntopjets_Data_copy__47->GetYaxis()->SetTitleFont(42);
   h_b_ntopjets_Data_copy__47->GetZaxis()->SetLabelFont(42);
   h_b_ntopjets_Data_copy__47->GetZaxis()->SetLabelSize(0.035);
   h_b_ntopjets_Data_copy__47->GetZaxis()->SetTitleSize(0.035);
   h_b_ntopjets_Data_copy__47->GetZaxis()->SetTitleFont(42);
   h_b_ntopjets_Data_copy__47->Draw("");
   
   TH1D *h_b_ntopjets_Data_copy__48 = new TH1D("h_b_ntopjets_Data_copy__48","",5,1,6);
   h_b_ntopjets_Data_copy__48->SetMinimum(-1);
   h_b_ntopjets_Data_copy__48->SetMaximum(1);
   h_b_ntopjets_Data_copy__48->SetEntries(5);
   h_b_ntopjets_Data_copy__48->SetDirectory(0);
   h_b_ntopjets_Data_copy__48->SetStats(0);

   ci = TColor::GetColor("#ff0000");
   h_b_ntopjets_Data_copy__48->SetLineColor(ci);
   h_b_ntopjets_Data_copy__48->SetMarkerStyle(7);
   h_b_ntopjets_Data_copy__48->GetXaxis()->SetTitle("Number of Top jets");
   h_b_ntopjets_Data_copy__48->GetXaxis()->SetRange(1,5);
   h_b_ntopjets_Data_copy__48->GetXaxis()->SetLabelFont(42);
   h_b_ntopjets_Data_copy__48->GetXaxis()->SetLabelOffset(0.02);
   h_b_ntopjets_Data_copy__48->GetXaxis()->SetLabelSize(0.14);
   h_b_ntopjets_Data_copy__48->GetXaxis()->SetTitleSize(0.15);
   h_b_ntopjets_Data_copy__48->GetXaxis()->SetTickLength(0.12);
   h_b_ntopjets_Data_copy__48->GetXaxis()->SetTitleFont(42);
   h_b_ntopjets_Data_copy__48->GetYaxis()->SetTitle("(Data-MC)/MC");
   h_b_ntopjets_Data_copy__48->GetYaxis()->SetNdivisions(8);
   h_b_ntopjets_Data_copy__48->GetYaxis()->SetLabelFont(42);
   h_b_ntopjets_Data_copy__48->GetYaxis()->SetLabelSize(0.07);
   h_b_ntopjets_Data_copy__48->GetYaxis()->SetTitleSize(0.08);
   h_b_ntopjets_Data_copy__48->GetYaxis()->SetTitleOffset(0.3);
   h_b_ntopjets_Data_copy__48->GetYaxis()->SetTitleFont(42);
   h_b_ntopjets_Data_copy__48->GetZaxis()->SetLabelFont(42);
   h_b_ntopjets_Data_copy__48->GetZaxis()->SetLabelSize(0.035);
   h_b_ntopjets_Data_copy__48->GetZaxis()->SetTitleSize(0.035);
   h_b_ntopjets_Data_copy__48->GetZaxis()->SetTitleFont(42);
   h_b_ntopjets_Data_copy__48->Draw("same");
   ratio->Modified();
   c->cd();
   TLatex *   tex = new TLatex(0.9,0.925,"36.8 fb^{-1} (13 TeV)");
tex->SetNDC();
   tex->SetTextAlign(31);
   tex->SetTextFont(42);
   tex->SetTextSize(0.045);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.1,0.925,"CMS");
tex->SetNDC();
   tex->SetTextFont(61);
   tex->SetTextSize(0.045);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.18,0.925,"Preliminary");
tex->SetNDC();
   tex->SetTextFont(52);
   tex->SetTextSize(0.0342);
   tex->SetLineWidth(2);
   tex->Draw();
   
   TLegend *leg = new TLegend(0.6,0.6,0.85,0.85,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetTextSize(0.03);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(1001);
   TLegendEntry *entry=leg->AddEntry("h_b_ntopjets_MC_LL","LL","f");
   entry->SetFillColor(2);
   entry->SetFillStyle(1001);
   entry->SetLineColor(2);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("h_b_ntopjets_MC_HadTau","HadTau","f");
   entry->SetFillColor(3);
   entry->SetFillStyle(1001);
   entry->SetLineColor(3);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("h_b_ntopjets_MC_Zinv","Zinv","f");
   entry->SetFillColor(4);
   entry->SetFillStyle(1001);
   entry->SetLineColor(4);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("h_b_ntopjets_MC_QCD","QCD","f");
   entry->SetFillColor(5);
   entry->SetFillStyle(1001);
   entry->SetLineColor(5);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("h_b_ntopjets_MC_TTZ","TTZ","f");
   entry->SetFillColor(6);
   entry->SetFillStyle(1001);
   entry->SetLineColor(6);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("h_b_ntopjets_Data","Data","l");

   ci = TColor::GetColor("#000099");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   leg->Draw();
   c->Modified();
   c->cd();
   c->SetSelected(c);
}
