void _nbjets_SFCheck()
{
//=========Macro generated from canvas: c/A Simple Graph Example
//=========  (Wed Oct 12 14:49:48 2016) by ROOT version6.06/01
   TCanvas *c = new TCanvas("c", "A Simple Graph Example",0,0,700,500);
   gStyle->SetOptStat(0);
   c->SetHighLightColor(2);
   c->Range(0,0,1,1);
   c->SetFillColor(0);
   c->SetBorderMode(0);
   c->SetBorderSize(2);
   c->SetFrameBorderMode(0);
  
// ------------>Primitives in pad: 
   TPad *pad = new TPad("", "",0,0.2,1,1);
   pad->Draw();
   pad->cd();
   pad->Range(-0.625,-77.93915,5.625,15509.89);
   pad->SetFillColor(0);
   pad->SetBorderMode(0);
   pad->SetBorderSize(5);
   pad->SetBottomMargin(0.005);
   pad->SetFrameBorderMode(0);
   pad->SetFrameBorderMode(0);
   
   TH1D *h_b_nbjets_Data__43 = new TH1D("h_b_nbjets_Data__43","",5,1,6);
   h_b_nbjets_Data__43->SetBinContent(1,13172);
   h_b_nbjets_Data__43->SetBinContent(2,4109);
   h_b_nbjets_Data__43->SetBinContent(3,472);
   h_b_nbjets_Data__43->SetBinContent(4,39);
   h_b_nbjets_Data__43->SetBinContent(5,1);
   h_b_nbjets_Data__43->SetBinError(1,114.7693);
   h_b_nbjets_Data__43->SetBinError(2,64.10148);
   h_b_nbjets_Data__43->SetBinError(3,21.72556);
   h_b_nbjets_Data__43->SetBinError(4,6.244998);
   h_b_nbjets_Data__43->SetBinError(5,1);
   h_b_nbjets_Data__43->SetEntries(17793);
   h_b_nbjets_Data__43->SetLineWidth(3);
   h_b_nbjets_Data__43->GetXaxis()->SetTitle("Number of B Jets");
   h_b_nbjets_Data__43->GetXaxis()->SetRange(0,4);
   h_b_nbjets_Data__43->GetXaxis()->SetLabelFont(42);
   h_b_nbjets_Data__43->GetXaxis()->SetLabelSize(0.035);
   h_b_nbjets_Data__43->GetXaxis()->SetTitleSize(0.035);
   h_b_nbjets_Data__43->GetXaxis()->SetTitleFont(42);
   h_b_nbjets_Data__43->GetYaxis()->SetLabelFont(42);
   h_b_nbjets_Data__43->GetYaxis()->SetLabelSize(0.035);
   h_b_nbjets_Data__43->GetYaxis()->SetTitleSize(0.035);
   h_b_nbjets_Data__43->GetYaxis()->SetTitleFont(42);
   h_b_nbjets_Data__43->GetZaxis()->SetLabelFont(42);
   h_b_nbjets_Data__43->GetZaxis()->SetLabelSize(0.035);
   h_b_nbjets_Data__43->GetZaxis()->SetTitleSize(0.035);
   h_b_nbjets_Data__43->GetZaxis()->SetTitleFont(42);
   h_b_nbjets_Data__43->Draw("e0");
   
   THStack *hs_MC = new THStack();
   hs_MC->SetName("hs_MC");
   hs_MC->SetTitle("");
   
   TH1F *hs_MC_stack_7 = new TH1F("hs_MC_stack_7","",5,1,6);
   hs_MC_stack_7->SetMinimum(0);
   hs_MC_stack_7->SetMaximum(16632.36);
   hs_MC_stack_7->SetDirectory(0);
   hs_MC_stack_7->SetStats(0);

   Int_t ci;      // for color index setting
   TColor *color; // for color definition with alpha
   ci = TColor::GetColor("#000099");
   hs_MC_stack_7->SetLineColor(ci);
   hs_MC_stack_7->GetXaxis()->SetLabelFont(42);
   hs_MC_stack_7->GetXaxis()->SetLabelSize(0.035);
   hs_MC_stack_7->GetXaxis()->SetTitleSize(0.035);
   hs_MC_stack_7->GetXaxis()->SetTitleFont(42);
   hs_MC_stack_7->GetYaxis()->SetLabelFont(42);
   hs_MC_stack_7->GetYaxis()->SetLabelSize(0.035);
   hs_MC_stack_7->GetYaxis()->SetTitleSize(0.035);
   hs_MC_stack_7->GetYaxis()->SetTitleFont(42);
   hs_MC_stack_7->GetZaxis()->SetLabelFont(42);
   hs_MC_stack_7->GetZaxis()->SetLabelSize(0.035);
   hs_MC_stack_7->GetZaxis()->SetTitleSize(0.035);
   hs_MC_stack_7->GetZaxis()->SetTitleFont(42);
   hs_MC->SetHistogram(hs_MC_stack_7);
   
   
   TH1D *h_b_nbjets_MC_TTJets__44 = new TH1D("h_b_nbjets_MC_TTJets__44","",5,1,6);
   h_b_nbjets_MC_TTJets__44->SetBinContent(1,10744.61);
   h_b_nbjets_MC_TTJets__44->SetBinContent(2,5279.308);
   h_b_nbjets_MC_TTJets__44->SetBinContent(3,675.5082);
   h_b_nbjets_MC_TTJets__44->SetBinContent(4,51.25629);
   h_b_nbjets_MC_TTJets__44->SetBinContent(5,3.828536);
   h_b_nbjets_MC_TTJets__44->SetBinContent(6,0.3252452);
   h_b_nbjets_MC_TTJets__44->SetBinError(1,21.39465);
   h_b_nbjets_MC_TTJets__44->SetBinError(2,13.76013);
   h_b_nbjets_MC_TTJets__44->SetBinError(3,4.701013);
   h_b_nbjets_MC_TTJets__44->SetBinError(4,1.242585);
   h_b_nbjets_MC_TTJets__44->SetBinError(5,0.3251357);
   h_b_nbjets_MC_TTJets__44->SetBinError(6,0.09205895);
   h_b_nbjets_MC_TTJets__44->SetEntries(432226);
   h_b_nbjets_MC_TTJets__44->SetFillColor(2);
   h_b_nbjets_MC_TTJets__44->SetLineColor(2);
   h_b_nbjets_MC_TTJets__44->GetXaxis()->SetLabelFont(42);
   h_b_nbjets_MC_TTJets__44->GetXaxis()->SetLabelSize(0.035);
   h_b_nbjets_MC_TTJets__44->GetXaxis()->SetTitleSize(0.035);
   h_b_nbjets_MC_TTJets__44->GetXaxis()->SetTitleFont(42);
   h_b_nbjets_MC_TTJets__44->GetYaxis()->SetLabelFont(42);
   h_b_nbjets_MC_TTJets__44->GetYaxis()->SetLabelSize(0.035);
   h_b_nbjets_MC_TTJets__44->GetYaxis()->SetTitleSize(0.035);
   h_b_nbjets_MC_TTJets__44->GetYaxis()->SetTitleFont(42);
   h_b_nbjets_MC_TTJets__44->GetZaxis()->SetLabelFont(42);
   h_b_nbjets_MC_TTJets__44->GetZaxis()->SetLabelSize(0.035);
   h_b_nbjets_MC_TTJets__44->GetZaxis()->SetTitleSize(0.035);
   h_b_nbjets_MC_TTJets__44->GetZaxis()->SetTitleFont(42);
   hs_MC->Add(h_b_nbjets_MC_TTJets,"");
   
   TH1D *h_b_nbjets_MC_ST__45 = new TH1D("h_b_nbjets_MC_ST__45","",5,1,6);
   h_b_nbjets_MC_ST__45->SetBinContent(1,1146.911);
   h_b_nbjets_MC_ST__45->SetBinContent(2,422.0393);
   h_b_nbjets_MC_ST__45->SetBinContent(3,50.42515);
   h_b_nbjets_MC_ST__45->SetBinContent(4,5.791791);
   h_b_nbjets_MC_ST__45->SetBinContent(5,0.2691315);
   h_b_nbjets_MC_ST__45->SetBinError(1,22.8781);
   h_b_nbjets_MC_ST__45->SetBinError(2,12.88728);
   h_b_nbjets_MC_ST__45->SetBinError(3,4.237558);
   h_b_nbjets_MC_ST__45->SetBinError(4,1.371105);
   h_b_nbjets_MC_ST__45->SetBinError(5,0.2691315);
   h_b_nbjets_MC_ST__45->SetEntries(3788);
   h_b_nbjets_MC_ST__45->SetFillColor(3);
   h_b_nbjets_MC_ST__45->SetLineColor(3);
   h_b_nbjets_MC_ST__45->GetXaxis()->SetLabelFont(42);
   h_b_nbjets_MC_ST__45->GetXaxis()->SetLabelSize(0.035);
   h_b_nbjets_MC_ST__45->GetXaxis()->SetTitleSize(0.035);
   h_b_nbjets_MC_ST__45->GetXaxis()->SetTitleFont(42);
   h_b_nbjets_MC_ST__45->GetYaxis()->SetLabelFont(42);
   h_b_nbjets_MC_ST__45->GetYaxis()->SetLabelSize(0.035);
   h_b_nbjets_MC_ST__45->GetYaxis()->SetTitleSize(0.035);
   h_b_nbjets_MC_ST__45->GetYaxis()->SetTitleFont(42);
   h_b_nbjets_MC_ST__45->GetZaxis()->SetLabelFont(42);
   h_b_nbjets_MC_ST__45->GetZaxis()->SetLabelSize(0.035);
   h_b_nbjets_MC_ST__45->GetZaxis()->SetTitleSize(0.035);
   h_b_nbjets_MC_ST__45->GetZaxis()->SetTitleFont(42);
   hs_MC->Add(h_b_nbjets_MC_ST,"");
   
   TH1D *h_b_nbjets_MC_WJets__46 = new TH1D("h_b_nbjets_MC_WJets__46","",5,1,6);
   h_b_nbjets_MC_WJets__46->SetBinContent(1,3948.828);
   h_b_nbjets_MC_WJets__46->SetBinContent(2,375.7643);
   h_b_nbjets_MC_WJets__46->SetBinContent(3,22.2763);
   h_b_nbjets_MC_WJets__46->SetBinContent(4,1.622317);
   h_b_nbjets_MC_WJets__46->SetBinContent(5,0.1198405);
   h_b_nbjets_MC_WJets__46->SetBinContent(6,0.02399416);
   h_b_nbjets_MC_WJets__46->SetBinError(1,15.68902);
   h_b_nbjets_MC_WJets__46->SetBinError(2,4.295925);
   h_b_nbjets_MC_WJets__46->SetBinError(3,0.8926728);
   h_b_nbjets_MC_WJets__46->SetBinError(4,0.1728075);
   h_b_nbjets_MC_WJets__46->SetBinError(5,0.02360539);
   h_b_nbjets_MC_WJets__46->SetBinError(6,0.01013181);
   h_b_nbjets_MC_WJets__46->SetEntries(240692);
   h_b_nbjets_MC_WJets__46->SetFillColor(4);
   h_b_nbjets_MC_WJets__46->SetLineColor(4);
   h_b_nbjets_MC_WJets__46->GetXaxis()->SetLabelFont(42);
   h_b_nbjets_MC_WJets__46->GetXaxis()->SetLabelSize(0.035);
   h_b_nbjets_MC_WJets__46->GetXaxis()->SetTitleSize(0.035);
   h_b_nbjets_MC_WJets__46->GetXaxis()->SetTitleFont(42);
   h_b_nbjets_MC_WJets__46->GetYaxis()->SetLabelFont(42);
   h_b_nbjets_MC_WJets__46->GetYaxis()->SetLabelSize(0.035);
   h_b_nbjets_MC_WJets__46->GetYaxis()->SetTitleSize(0.035);
   h_b_nbjets_MC_WJets__46->GetYaxis()->SetTitleFont(42);
   h_b_nbjets_MC_WJets__46->GetZaxis()->SetLabelFont(42);
   h_b_nbjets_MC_WJets__46->GetZaxis()->SetLabelSize(0.035);
   h_b_nbjets_MC_WJets__46->GetZaxis()->SetTitleSize(0.035);
   h_b_nbjets_MC_WJets__46->GetZaxis()->SetTitleFont(42);
   hs_MC->Add(h_b_nbjets_MC_WJets,"");
   hs_MC->Draw("same hist");
   
   TH1D *h_b_nbjets_Data__47 = new TH1D("h_b_nbjets_Data__47","",5,1,6);
   h_b_nbjets_Data__47->SetBinContent(1,13172);
   h_b_nbjets_Data__47->SetBinContent(2,4109);
   h_b_nbjets_Data__47->SetBinContent(3,472);
   h_b_nbjets_Data__47->SetBinContent(4,39);
   h_b_nbjets_Data__47->SetBinContent(5,1);
   h_b_nbjets_Data__47->SetBinError(1,114.7693);
   h_b_nbjets_Data__47->SetBinError(2,64.10148);
   h_b_nbjets_Data__47->SetBinError(3,21.72556);
   h_b_nbjets_Data__47->SetBinError(4,6.244998);
   h_b_nbjets_Data__47->SetBinError(5,1);
   h_b_nbjets_Data__47->SetEntries(17793);
   h_b_nbjets_Data__47->SetLineWidth(3);
   h_b_nbjets_Data__47->GetXaxis()->SetTitle("Number of B Jets");
   h_b_nbjets_Data__47->GetXaxis()->SetRange(0,4);
   h_b_nbjets_Data__47->GetXaxis()->SetLabelFont(42);
   h_b_nbjets_Data__47->GetXaxis()->SetLabelSize(0.035);
   h_b_nbjets_Data__47->GetXaxis()->SetTitleSize(0.035);
   h_b_nbjets_Data__47->GetXaxis()->SetTitleFont(42);
   h_b_nbjets_Data__47->GetYaxis()->SetLabelFont(42);
   h_b_nbjets_Data__47->GetYaxis()->SetLabelSize(0.035);
   h_b_nbjets_Data__47->GetYaxis()->SetTitleSize(0.035);
   h_b_nbjets_Data__47->GetYaxis()->SetTitleFont(42);
   h_b_nbjets_Data__47->GetZaxis()->SetLabelFont(42);
   h_b_nbjets_Data__47->GetZaxis()->SetLabelSize(0.035);
   h_b_nbjets_Data__47->GetZaxis()->SetTitleSize(0.035);
   h_b_nbjets_Data__47->GetZaxis()->SetTitleFont(42);
   h_b_nbjets_Data__47->Draw("same e0");
   pad->Modified();
   c->cd();
  
// ------------>Primitives in pad: ratio
   TPad *ratio = new TPad("ratio", "",0,0,1,0.2);
   ratio->Draw();
   ratio->cd();
   ratio->Range(-0.625,-3.714286,5.625,2);
   ratio->SetFillColor(0);
   ratio->SetBorderMode(0);
   ratio->SetBorderSize(5);
   ratio->SetTopMargin(0);
   ratio->SetBottomMargin(0.3);
   ratio->SetFrameBorderMode(0);
   ratio->SetFrameBorderMode(0);
   
   TH1D *h_b_nbjets_Data_copy__48 = new TH1D("h_b_nbjets_Data_copy__48","",5,1,6);
   h_b_nbjets_Data_copy__48->SetBinContent(1,-0.1684524);
   h_b_nbjets_Data_copy__48->SetBinContent(2,-0.3238564);
   h_b_nbjets_Data_copy__48->SetBinContent(3,-0.3691608);
   h_b_nbjets_Data_copy__48->SetBinContent(4,-0.3352695);
   h_b_nbjets_Data_copy__48->SetBinContent(5,-0.7628932);
   h_b_nbjets_Data_copy__48->SetBinContent(6,-1);
   h_b_nbjets_Data_copy__48->SetBinError(1,0.00758456);
   h_b_nbjets_Data_copy__48->SetBinError(2,0.01106554);
   h_b_nbjets_Data_copy__48->SetBinError(3,0.03043112);
   h_b_nbjets_Data_copy__48->SetBinError(4,0.1115619);
   h_b_nbjets_Data_copy__48->SetBinError(5,0.2685394);
   h_b_nbjets_Data_copy__48->SetBinError(6,0.3750355);
   h_b_nbjets_Data_copy__48->SetMinimum(-2);
   h_b_nbjets_Data_copy__48->SetMaximum(2);
   h_b_nbjets_Data_copy__48->SetEntries(1.196739);
   h_b_nbjets_Data_copy__48->SetDirectory(0);
   h_b_nbjets_Data_copy__48->SetStats(0);
   h_b_nbjets_Data_copy__48->SetLineWidth(3);
   h_b_nbjets_Data_copy__48->SetMarkerStyle(7);
   h_b_nbjets_Data_copy__48->GetXaxis()->SetTitle("Number of B Jets");
   h_b_nbjets_Data_copy__48->GetXaxis()->SetRange(0,4);
   h_b_nbjets_Data_copy__48->GetXaxis()->SetLabelFont(42);
   h_b_nbjets_Data_copy__48->GetXaxis()->SetLabelOffset(0.02);
   h_b_nbjets_Data_copy__48->GetXaxis()->SetLabelSize(0.14);
   h_b_nbjets_Data_copy__48->GetXaxis()->SetTitleSize(0.15);
   h_b_nbjets_Data_copy__48->GetXaxis()->SetTickLength(0.12);
   h_b_nbjets_Data_copy__48->GetXaxis()->SetTitleFont(42);
   h_b_nbjets_Data_copy__48->GetYaxis()->SetTitle("(Data-MC)/MC");
   h_b_nbjets_Data_copy__48->GetYaxis()->SetNdivisions(8);
   h_b_nbjets_Data_copy__48->GetYaxis()->SetLabelFont(42);
   h_b_nbjets_Data_copy__48->GetYaxis()->SetLabelSize(0.07);
   h_b_nbjets_Data_copy__48->GetYaxis()->SetTitleSize(0.08);
   h_b_nbjets_Data_copy__48->GetYaxis()->SetTitleOffset(0.3);
   h_b_nbjets_Data_copy__48->GetYaxis()->SetTitleFont(42);
   h_b_nbjets_Data_copy__48->GetZaxis()->SetLabelFont(42);
   h_b_nbjets_Data_copy__48->GetZaxis()->SetLabelSize(0.035);
   h_b_nbjets_Data_copy__48->GetZaxis()->SetTitleSize(0.035);
   h_b_nbjets_Data_copy__48->GetZaxis()->SetTitleFont(42);
   h_b_nbjets_Data_copy__48->Draw("");
   
   TH1D *h_b_nbjets_Data_copy__49 = new TH1D("h_b_nbjets_Data_copy__49","",5,1,6);
   h_b_nbjets_Data_copy__49->SetMinimum(-2);
   h_b_nbjets_Data_copy__49->SetMaximum(2);
   h_b_nbjets_Data_copy__49->SetEntries(5);
   h_b_nbjets_Data_copy__49->SetDirectory(0);
   h_b_nbjets_Data_copy__49->SetStats(0);

   ci = TColor::GetColor("#ff0000");
   h_b_nbjets_Data_copy__49->SetLineColor(ci);
   h_b_nbjets_Data_copy__49->SetMarkerStyle(7);
   h_b_nbjets_Data_copy__49->GetXaxis()->SetTitle("Number of B Jets");
   h_b_nbjets_Data_copy__49->GetXaxis()->SetRange(0,4);
   h_b_nbjets_Data_copy__49->GetXaxis()->SetLabelFont(42);
   h_b_nbjets_Data_copy__49->GetXaxis()->SetLabelOffset(0.02);
   h_b_nbjets_Data_copy__49->GetXaxis()->SetLabelSize(0.14);
   h_b_nbjets_Data_copy__49->GetXaxis()->SetTitleSize(0.15);
   h_b_nbjets_Data_copy__49->GetXaxis()->SetTickLength(0.12);
   h_b_nbjets_Data_copy__49->GetXaxis()->SetTitleFont(42);
   h_b_nbjets_Data_copy__49->GetYaxis()->SetTitle("(Data-MC)/MC");
   h_b_nbjets_Data_copy__49->GetYaxis()->SetNdivisions(8);
   h_b_nbjets_Data_copy__49->GetYaxis()->SetLabelFont(42);
   h_b_nbjets_Data_copy__49->GetYaxis()->SetLabelSize(0.07);
   h_b_nbjets_Data_copy__49->GetYaxis()->SetTitleSize(0.08);
   h_b_nbjets_Data_copy__49->GetYaxis()->SetTitleOffset(0.3);
   h_b_nbjets_Data_copy__49->GetYaxis()->SetTitleFont(42);
   h_b_nbjets_Data_copy__49->GetZaxis()->SetLabelFont(42);
   h_b_nbjets_Data_copy__49->GetZaxis()->SetLabelSize(0.035);
   h_b_nbjets_Data_copy__49->GetZaxis()->SetTitleSize(0.035);
   h_b_nbjets_Data_copy__49->GetZaxis()->SetTitleFont(42);
   h_b_nbjets_Data_copy__49->Draw("same");
   ratio->Modified();
   c->cd();
   TLatex *   tex = new TLatex(0.9,0.925,"12.9 fb^{-1} (13 TeV)");
tex->SetNDC();
   tex->SetTextAlign(31);
   tex->SetTextFont(42);
   tex->SetTextSize(0.045);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.1,0.925,"CMS");
tex->SetNDC();
   tex->SetTextFont(61);
   tex->SetTextSize(0.045);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.18,0.925,"Simulation");
tex->SetNDC();
   tex->SetTextFont(52);
   tex->SetTextSize(0.0342);
   tex->SetLineWidth(2);
   tex->Draw();
   
   TLegend *leg = new TLegend(0.6,0.6,0.85,0.85,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetTextSize(0.03);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(1001);
   TLegendEntry *entry=leg->AddEntry("h_b_nbjets_MC_TTJets","TTJets","f");
   entry->SetFillColor(2);
   entry->SetFillStyle(1001);
   entry->SetLineColor(2);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("h_b_nbjets_MC_ST","ST","f");
   entry->SetFillColor(3);
   entry->SetFillStyle(1001);
   entry->SetLineColor(3);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("h_b_nbjets_MC_WJets","WJets","f");
   entry->SetFillColor(4);
   entry->SetFillStyle(1001);
   entry->SetLineColor(4);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("h_b_nbjets_Data","Data","l");

   ci = TColor::GetColor("#000099");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   leg->Draw();
   c->Modified();
   c->cd();
   c->SetSelected(c);
}
