void _ntopjets_SFCheck()
{
//=========Macro generated from canvas: c/A Simple Graph Example
//=========  (Wed Oct 12 14:49:48 2016) by ROOT version6.06/01
   TCanvas *c = new TCanvas("c", "A Simple Graph Example",0,0,700,500);
   gStyle->SetOptStat(0);
   c->SetHighLightColor(2);
   c->Range(0,0,1,1);
   c->SetFillColor(0);
   c->SetBorderMode(0);
   c->SetBorderSize(2);
   c->SetFrameBorderMode(0);
  
// ------------>Primitives in pad: 
   TPad *pad = new TPad("", "",0,0.2,1,1);
   pad->Draw();
   pad->cd();
   pad->Range(-0.625,-64.56276,5.625,12847.99);
   pad->SetFillColor(0);
   pad->SetBorderMode(0);
   pad->SetBorderSize(5);
   pad->SetBottomMargin(0.005);
   pad->SetFrameBorderMode(0);
   pad->SetFrameBorderMode(0);
   
   TH1D *h_b_ntopjets_Data__36 = new TH1D("h_b_ntopjets_Data__36","",5,1,6);
   h_b_ntopjets_Data__36->SetBinContent(0,10902);
   h_b_ntopjets_Data__36->SetBinContent(1,6149);
   h_b_ntopjets_Data__36->SetBinContent(2,724);
   h_b_ntopjets_Data__36->SetBinContent(3,18);
   h_b_ntopjets_Data__36->SetBinError(0,104.4126);
   h_b_ntopjets_Data__36->SetBinError(1,78.41556);
   h_b_ntopjets_Data__36->SetBinError(2,26.90725);
   h_b_ntopjets_Data__36->SetBinError(3,4.242641);
   h_b_ntopjets_Data__36->SetEntries(17793);
   h_b_ntopjets_Data__36->SetLineWidth(3);
   h_b_ntopjets_Data__36->GetXaxis()->SetTitle("Number of Top jets");
   h_b_ntopjets_Data__36->GetXaxis()->SetRange(0,4);
   h_b_ntopjets_Data__36->GetXaxis()->SetLabelFont(42);
   h_b_ntopjets_Data__36->GetXaxis()->SetLabelSize(0.035);
   h_b_ntopjets_Data__36->GetXaxis()->SetTitleSize(0.035);
   h_b_ntopjets_Data__36->GetXaxis()->SetTitleFont(42);
   h_b_ntopjets_Data__36->GetYaxis()->SetLabelFont(42);
   h_b_ntopjets_Data__36->GetYaxis()->SetLabelSize(0.035);
   h_b_ntopjets_Data__36->GetYaxis()->SetTitleSize(0.035);
   h_b_ntopjets_Data__36->GetYaxis()->SetTitleFont(42);
   h_b_ntopjets_Data__36->GetZaxis()->SetLabelFont(42);
   h_b_ntopjets_Data__36->GetZaxis()->SetLabelSize(0.035);
   h_b_ntopjets_Data__36->GetZaxis()->SetTitleSize(0.035);
   h_b_ntopjets_Data__36->GetZaxis()->SetTitleFont(42);
   h_b_ntopjets_Data__36->Draw("e0");
   
   THStack *hs_MC = new THStack();
   hs_MC->SetName("hs_MC");
   hs_MC->SetTitle("");
   
   TH1F *hs_MC_stack_6 = new TH1F("hs_MC_stack_6","",5,1,6);
   hs_MC_stack_6->SetMinimum(0);
   hs_MC_stack_6->SetMaximum(9851.629);
   hs_MC_stack_6->SetDirectory(0);
   hs_MC_stack_6->SetStats(0);

   Int_t ci;      // for color index setting
   TColor *color; // for color definition with alpha
   ci = TColor::GetColor("#000099");
   hs_MC_stack_6->SetLineColor(ci);
   hs_MC_stack_6->GetXaxis()->SetLabelFont(42);
   hs_MC_stack_6->GetXaxis()->SetLabelSize(0.035);
   hs_MC_stack_6->GetXaxis()->SetTitleSize(0.035);
   hs_MC_stack_6->GetXaxis()->SetTitleFont(42);
   hs_MC_stack_6->GetYaxis()->SetLabelFont(42);
   hs_MC_stack_6->GetYaxis()->SetLabelSize(0.035);
   hs_MC_stack_6->GetYaxis()->SetTitleSize(0.035);
   hs_MC_stack_6->GetYaxis()->SetTitleFont(42);
   hs_MC_stack_6->GetZaxis()->SetLabelFont(42);
   hs_MC_stack_6->GetZaxis()->SetLabelSize(0.035);
   hs_MC_stack_6->GetZaxis()->SetTitleSize(0.035);
   hs_MC_stack_6->GetZaxis()->SetTitleFont(42);
   hs_MC->SetHistogram(hs_MC_stack_6);
   
   
   TH1D *h_b_ntopjets_MC_TTJets__37 = new TH1D("h_b_ntopjets_MC_TTJets__37","",5,1,6);
   h_b_ntopjets_MC_TTJets__37->SetBinContent(0,7642.69);
   h_b_ntopjets_MC_TTJets__37->SetBinContent(1,7880.848);
   h_b_ntopjets_MC_TTJets__37->SetBinContent(2,1181.157);
   h_b_ntopjets_MC_TTJets__37->SetBinContent(3,48.20527);
   h_b_ntopjets_MC_TTJets__37->SetBinContent(4,1.931159);
   h_b_ntopjets_MC_TTJets__37->SetBinError(0,17.22725);
   h_b_ntopjets_MC_TTJets__37->SetBinError(1,17.95592);
   h_b_ntopjets_MC_TTJets__37->SetBinError(2,7.035777);
   h_b_ntopjets_MC_TTJets__37->SetBinError(3,1.430861);
   h_b_ntopjets_MC_TTJets__37->SetBinError(4,0.2953209);
   h_b_ntopjets_MC_TTJets__37->SetEntries(432226);
   h_b_ntopjets_MC_TTJets__37->SetFillColor(2);
   h_b_ntopjets_MC_TTJets__37->SetLineColor(2);
   h_b_ntopjets_MC_TTJets__37->GetXaxis()->SetLabelFont(42);
   h_b_ntopjets_MC_TTJets__37->GetXaxis()->SetLabelSize(0.035);
   h_b_ntopjets_MC_TTJets__37->GetXaxis()->SetTitleSize(0.035);
   h_b_ntopjets_MC_TTJets__37->GetXaxis()->SetTitleFont(42);
   h_b_ntopjets_MC_TTJets__37->GetYaxis()->SetLabelFont(42);
   h_b_ntopjets_MC_TTJets__37->GetYaxis()->SetLabelSize(0.035);
   h_b_ntopjets_MC_TTJets__37->GetYaxis()->SetTitleSize(0.035);
   h_b_ntopjets_MC_TTJets__37->GetYaxis()->SetTitleFont(42);
   h_b_ntopjets_MC_TTJets__37->GetZaxis()->SetLabelFont(42);
   h_b_ntopjets_MC_TTJets__37->GetZaxis()->SetLabelSize(0.035);
   h_b_ntopjets_MC_TTJets__37->GetZaxis()->SetTitleSize(0.035);
   h_b_ntopjets_MC_TTJets__37->GetZaxis()->SetTitleFont(42);
   hs_MC->Add(h_b_ntopjets_MC_TTJets,"");
   
   TH1D *h_b_ntopjets_MC_ST__38 = new TH1D("h_b_ntopjets_MC_ST__38","",5,1,6);
   h_b_ntopjets_MC_ST__38->SetBinContent(0,964.0321);
   h_b_ntopjets_MC_ST__38->SetBinContent(1,612.1082);
   h_b_ntopjets_MC_ST__38->SetBinContent(2,48.28817);
   h_b_ntopjets_MC_ST__38->SetBinContent(3,1.0078);
   h_b_ntopjets_MC_ST__38->SetBinError(0,20.41891);
   h_b_ntopjets_MC_ST__38->SetBinError(1,16.42609);
   h_b_ntopjets_MC_ST__38->SetBinError(2,4.701956);
   h_b_ntopjets_MC_ST__38->SetBinError(3,0.7361001);
   h_b_ntopjets_MC_ST__38->SetEntries(3788);
   h_b_ntopjets_MC_ST__38->SetFillColor(3);
   h_b_ntopjets_MC_ST__38->SetLineColor(3);
   h_b_ntopjets_MC_ST__38->GetXaxis()->SetLabelFont(42);
   h_b_ntopjets_MC_ST__38->GetXaxis()->SetLabelSize(0.035);
   h_b_ntopjets_MC_ST__38->GetXaxis()->SetTitleSize(0.035);
   h_b_ntopjets_MC_ST__38->GetXaxis()->SetTitleFont(42);
   h_b_ntopjets_MC_ST__38->GetYaxis()->SetLabelFont(42);
   h_b_ntopjets_MC_ST__38->GetYaxis()->SetLabelSize(0.035);
   h_b_ntopjets_MC_ST__38->GetYaxis()->SetTitleSize(0.035);
   h_b_ntopjets_MC_ST__38->GetYaxis()->SetTitleFont(42);
   h_b_ntopjets_MC_ST__38->GetZaxis()->SetLabelFont(42);
   h_b_ntopjets_MC_ST__38->GetZaxis()->SetLabelSize(0.035);
   h_b_ntopjets_MC_ST__38->GetZaxis()->SetTitleSize(0.035);
   h_b_ntopjets_MC_ST__38->GetZaxis()->SetTitleFont(42);
   hs_MC->Add(h_b_ntopjets_MC_ST,"");
   
   TH1D *h_b_ntopjets_MC_WJets__39 = new TH1D("h_b_ntopjets_MC_WJets__39","",5,1,6);
   h_b_ntopjets_MC_WJets__39->SetBinContent(0,3390.084);
   h_b_ntopjets_MC_WJets__39->SetBinContent(1,889.5476);
   h_b_ntopjets_MC_WJets__39->SetBinContent(2,66.51114);
   h_b_ntopjets_MC_WJets__39->SetBinContent(3,2.409212);
   h_b_ntopjets_MC_WJets__39->SetBinContent(4,0.08294161);
   h_b_ntopjets_MC_WJets__39->SetBinError(0,14.74009);
   h_b_ntopjets_MC_WJets__39->SetBinError(1,6.80006);
   h_b_ntopjets_MC_WJets__39->SetBinError(2,1.375454);
   h_b_ntopjets_MC_WJets__39->SetBinError(3,0.1563943);
   h_b_ntopjets_MC_WJets__39->SetBinError(4,0.01680852);
   h_b_ntopjets_MC_WJets__39->SetEntries(240692);
   h_b_ntopjets_MC_WJets__39->SetFillColor(4);
   h_b_ntopjets_MC_WJets__39->SetLineColor(4);
   h_b_ntopjets_MC_WJets__39->GetXaxis()->SetLabelFont(42);
   h_b_ntopjets_MC_WJets__39->GetXaxis()->SetLabelSize(0.035);
   h_b_ntopjets_MC_WJets__39->GetXaxis()->SetTitleSize(0.035);
   h_b_ntopjets_MC_WJets__39->GetXaxis()->SetTitleFont(42);
   h_b_ntopjets_MC_WJets__39->GetYaxis()->SetLabelFont(42);
   h_b_ntopjets_MC_WJets__39->GetYaxis()->SetLabelSize(0.035);
   h_b_ntopjets_MC_WJets__39->GetYaxis()->SetTitleSize(0.035);
   h_b_ntopjets_MC_WJets__39->GetYaxis()->SetTitleFont(42);
   h_b_ntopjets_MC_WJets__39->GetZaxis()->SetLabelFont(42);
   h_b_ntopjets_MC_WJets__39->GetZaxis()->SetLabelSize(0.035);
   h_b_ntopjets_MC_WJets__39->GetZaxis()->SetTitleSize(0.035);
   h_b_ntopjets_MC_WJets__39->GetZaxis()->SetTitleFont(42);
   hs_MC->Add(h_b_ntopjets_MC_WJets,"");
   hs_MC->Draw("same hist");
   
   TH1D *h_b_ntopjets_Data__40 = new TH1D("h_b_ntopjets_Data__40","",5,1,6);
   h_b_ntopjets_Data__40->SetBinContent(0,10902);
   h_b_ntopjets_Data__40->SetBinContent(1,6149);
   h_b_ntopjets_Data__40->SetBinContent(2,724);
   h_b_ntopjets_Data__40->SetBinContent(3,18);
   h_b_ntopjets_Data__40->SetBinError(0,104.4126);
   h_b_ntopjets_Data__40->SetBinError(1,78.41556);
   h_b_ntopjets_Data__40->SetBinError(2,26.90725);
   h_b_ntopjets_Data__40->SetBinError(3,4.242641);
   h_b_ntopjets_Data__40->SetEntries(17793);
   h_b_ntopjets_Data__40->SetLineWidth(3);
   h_b_ntopjets_Data__40->GetXaxis()->SetTitle("Number of Top jets");
   h_b_ntopjets_Data__40->GetXaxis()->SetRange(0,4);
   h_b_ntopjets_Data__40->GetXaxis()->SetLabelFont(42);
   h_b_ntopjets_Data__40->GetXaxis()->SetLabelSize(0.035);
   h_b_ntopjets_Data__40->GetXaxis()->SetTitleSize(0.035);
   h_b_ntopjets_Data__40->GetXaxis()->SetTitleFont(42);
   h_b_ntopjets_Data__40->GetYaxis()->SetLabelFont(42);
   h_b_ntopjets_Data__40->GetYaxis()->SetLabelSize(0.035);
   h_b_ntopjets_Data__40->GetYaxis()->SetTitleSize(0.035);
   h_b_ntopjets_Data__40->GetYaxis()->SetTitleFont(42);
   h_b_ntopjets_Data__40->GetZaxis()->SetLabelFont(42);
   h_b_ntopjets_Data__40->GetZaxis()->SetLabelSize(0.035);
   h_b_ntopjets_Data__40->GetZaxis()->SetTitleSize(0.035);
   h_b_ntopjets_Data__40->GetZaxis()->SetTitleFont(42);
   h_b_ntopjets_Data__40->Draw("same e0");
   pad->Modified();
   c->cd();
  
// ------------>Primitives in pad: ratio
   TPad *ratio = new TPad("ratio", "",0,0,1,0.2);
   ratio->Draw();
   ratio->cd();
   ratio->Range(-0.625,-3.714286,5.625,2);
   ratio->SetFillColor(0);
   ratio->SetBorderMode(0);
   ratio->SetBorderSize(5);
   ratio->SetTopMargin(0);
   ratio->SetBottomMargin(0.3);
   ratio->SetFrameBorderMode(0);
   ratio->SetFrameBorderMode(0);
   
   TH1D *h_b_ntopjets_Data_copy__41 = new TH1D("h_b_ntopjets_Data_copy__41","",5,1,6);
   h_b_ntopjets_Data_copy__41->SetBinContent(0,-0.09125814);
   h_b_ntopjets_Data_copy__41->SetBinContent(1,-0.3446313);
   h_b_ntopjets_Data_copy__41->SetBinContent(2,-0.4413391);
   h_b_ntopjets_Data_copy__41->SetBinContent(3,-0.6513133);
   h_b_ntopjets_Data_copy__41->SetBinContent(4,-1);
   h_b_ntopjets_Data_copy__41->SetBinError(0,0.009070342);
   h_b_ntopjets_Data_copy__41->SetBinError(1,0.008829739);
   h_b_ntopjets_Data_copy__41->SetBinError(2,0.02198565);
   h_b_ntopjets_Data_copy__41->SetBinError(3,0.09028525);
   h_b_ntopjets_Data_copy__41->SetBinError(4,0.207697);
   h_b_ntopjets_Data_copy__41->SetMinimum(-2);
   h_b_ntopjets_Data_copy__41->SetMaximum(2);
   h_b_ntopjets_Data_copy__41->SetEntries(2.528542);
   h_b_ntopjets_Data_copy__41->SetDirectory(0);
   h_b_ntopjets_Data_copy__41->SetStats(0);
   h_b_ntopjets_Data_copy__41->SetLineWidth(3);
   h_b_ntopjets_Data_copy__41->SetMarkerStyle(7);
   h_b_ntopjets_Data_copy__41->GetXaxis()->SetTitle("Number of Top jets");
   h_b_ntopjets_Data_copy__41->GetXaxis()->SetRange(0,4);
   h_b_ntopjets_Data_copy__41->GetXaxis()->SetLabelFont(42);
   h_b_ntopjets_Data_copy__41->GetXaxis()->SetLabelOffset(0.02);
   h_b_ntopjets_Data_copy__41->GetXaxis()->SetLabelSize(0.14);
   h_b_ntopjets_Data_copy__41->GetXaxis()->SetTitleSize(0.15);
   h_b_ntopjets_Data_copy__41->GetXaxis()->SetTickLength(0.12);
   h_b_ntopjets_Data_copy__41->GetXaxis()->SetTitleFont(42);
   h_b_ntopjets_Data_copy__41->GetYaxis()->SetTitle("(Data-MC)/MC");
   h_b_ntopjets_Data_copy__41->GetYaxis()->SetNdivisions(8);
   h_b_ntopjets_Data_copy__41->GetYaxis()->SetLabelFont(42);
   h_b_ntopjets_Data_copy__41->GetYaxis()->SetLabelSize(0.07);
   h_b_ntopjets_Data_copy__41->GetYaxis()->SetTitleSize(0.08);
   h_b_ntopjets_Data_copy__41->GetYaxis()->SetTitleOffset(0.3);
   h_b_ntopjets_Data_copy__41->GetYaxis()->SetTitleFont(42);
   h_b_ntopjets_Data_copy__41->GetZaxis()->SetLabelFont(42);
   h_b_ntopjets_Data_copy__41->GetZaxis()->SetLabelSize(0.035);
   h_b_ntopjets_Data_copy__41->GetZaxis()->SetTitleSize(0.035);
   h_b_ntopjets_Data_copy__41->GetZaxis()->SetTitleFont(42);
   h_b_ntopjets_Data_copy__41->Draw("");
   
   TH1D *h_b_ntopjets_Data_copy__42 = new TH1D("h_b_ntopjets_Data_copy__42","",5,1,6);
   h_b_ntopjets_Data_copy__42->SetMinimum(-2);
   h_b_ntopjets_Data_copy__42->SetMaximum(2);
   h_b_ntopjets_Data_copy__42->SetEntries(5);
   h_b_ntopjets_Data_copy__42->SetDirectory(0);
   h_b_ntopjets_Data_copy__42->SetStats(0);

   ci = TColor::GetColor("#ff0000");
   h_b_ntopjets_Data_copy__42->SetLineColor(ci);
   h_b_ntopjets_Data_copy__42->SetMarkerStyle(7);
   h_b_ntopjets_Data_copy__42->GetXaxis()->SetTitle("Number of Top jets");
   h_b_ntopjets_Data_copy__42->GetXaxis()->SetRange(0,4);
   h_b_ntopjets_Data_copy__42->GetXaxis()->SetLabelFont(42);
   h_b_ntopjets_Data_copy__42->GetXaxis()->SetLabelOffset(0.02);
   h_b_ntopjets_Data_copy__42->GetXaxis()->SetLabelSize(0.14);
   h_b_ntopjets_Data_copy__42->GetXaxis()->SetTitleSize(0.15);
   h_b_ntopjets_Data_copy__42->GetXaxis()->SetTickLength(0.12);
   h_b_ntopjets_Data_copy__42->GetXaxis()->SetTitleFont(42);
   h_b_ntopjets_Data_copy__42->GetYaxis()->SetTitle("(Data-MC)/MC");
   h_b_ntopjets_Data_copy__42->GetYaxis()->SetNdivisions(8);
   h_b_ntopjets_Data_copy__42->GetYaxis()->SetLabelFont(42);
   h_b_ntopjets_Data_copy__42->GetYaxis()->SetLabelSize(0.07);
   h_b_ntopjets_Data_copy__42->GetYaxis()->SetTitleSize(0.08);
   h_b_ntopjets_Data_copy__42->GetYaxis()->SetTitleOffset(0.3);
   h_b_ntopjets_Data_copy__42->GetYaxis()->SetTitleFont(42);
   h_b_ntopjets_Data_copy__42->GetZaxis()->SetLabelFont(42);
   h_b_ntopjets_Data_copy__42->GetZaxis()->SetLabelSize(0.035);
   h_b_ntopjets_Data_copy__42->GetZaxis()->SetTitleSize(0.035);
   h_b_ntopjets_Data_copy__42->GetZaxis()->SetTitleFont(42);
   h_b_ntopjets_Data_copy__42->Draw("same");
   ratio->Modified();
   c->cd();
   TLatex *   tex = new TLatex(0.9,0.925,"12.9 fb^{-1} (13 TeV)");
tex->SetNDC();
   tex->SetTextAlign(31);
   tex->SetTextFont(42);
   tex->SetTextSize(0.045);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.1,0.925,"CMS");
tex->SetNDC();
   tex->SetTextFont(61);
   tex->SetTextSize(0.045);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.18,0.925,"Simulation");
tex->SetNDC();
   tex->SetTextFont(52);
   tex->SetTextSize(0.0342);
   tex->SetLineWidth(2);
   tex->Draw();
   
   TLegend *leg = new TLegend(0.6,0.6,0.85,0.85,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetTextSize(0.03);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(1001);
   TLegendEntry *entry=leg->AddEntry("h_b_ntopjets_MC_TTJets","TTJets","f");
   entry->SetFillColor(2);
   entry->SetFillStyle(1001);
   entry->SetLineColor(2);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("h_b_ntopjets_MC_ST","ST","f");
   entry->SetFillColor(3);
   entry->SetFillStyle(1001);
   entry->SetLineColor(3);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("h_b_ntopjets_MC_WJets","WJets","f");
   entry->SetFillColor(4);
   entry->SetFillStyle(1001);
   entry->SetLineColor(4);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("h_b_ntopjets_Data","Data","l");

   ci = TColor::GetColor("#000099");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   leg->Draw();
   c->Modified();
   c->cd();
   c->SetSelected(c);
}
